const actionTypes = {
  CREATE_COURSE: 'CREATE_COURSE',
  CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
  UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS',
  LOAD_COURSES_SUCCESS: 'LOAD_COURSES_SUCCESS',
  LOAD_AUTHORS_SUCCESS: 'LOAD_AUTHORS_SUCCESS',
  BEGIN_API_CALL: 'BEGIN_API_CALL',
};

export default actionTypes;
